#:import Path pathlib.Path

<AuthScreenView>
    BoxLayout:
        orientation: 'vertical'
        padding: "50dp"
        spacing: "50dp"
        
        AnchorLayout:
            anchor_x: "center"
            anchor_y: "top"
            size_hint: 1, 0.5

            BoxLayout:
                orientation: "horizontal"
                spacing: "50dp"
                size_hint: None, None
                size: "120dp", "80dp"

                Label:
                    text: "Llama"
                    font_size: "30sp"
                    size_hint: None, None
                    size: "50dp", "50dp"

                Image:
                    source: str(Path('Resource', 'lamma-icon.png'))
                    size_hint: None, None
                    size: "100dp", "100dp"

        TextInput:
            id: token_text_input
            height: "30dp"
            hint_text: "Your API TOKEN..."
            size_hint_y: None
            multiline: False
            background_color: "gray"
            hint_text_color: "white"
            
        Widget:	
            
        Button:
            height: "50dp"
            text: "Login"
            size_hint_y: None
            size_hint_x: 0.5
            font_size: "24sp"
            background_color: 255, 165, 0, 0.5
            background_normal: ''
            pos_hint: {"center_x": 0.5}
            on_press: root.login_click_button()

<Apopup>
    auto_dismiss: False
    size_hint: None, None
    height: "200dp"
    width: "250dp"
    title_size: "20sp"

    BoxLayout:
        orientation: "vertical"
        padding: "10dp"
        spacing: "10dp"

        Label:
            text: root.text
            font_size: "20sp"

        Button:
            text: "OK"
            font_size: 24
            on_release: root.dismiss()
            size_hint: 1, 0.5

