<AuthScreenView>
    BoxLayout:
        orientation: 'vertical'
        padding: "50dp"
        spacing: "50dp"
        
        Widget:
        
        Label:
            text: "ChatGPT"
            height: "20dp"
            size_hint: 1, 0.2
            halign: "center"
            font_size: "30sp"
            
        TextInput:
            height: "30dp"
            hint_text: "Your Token ChatGPT"
            size_hint_y: None
            multiline: False
            
        Widget:	
            
        Button:
            height: "50dp"
            text: "Login"
            size_hint_y: None
            size_hint_x: 0.5
            font_size: "24sp"
            pos_hint: {"center_x": 0.5}	
